apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acmeair-argocd
spec:
  destination:
    namespace: kamura-work
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app
    repoURL: https://github.com/rkyce/acmeair-manifests
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
