apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acmeair
spec:
  destination:
    namespace: argocd-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path:
    repoURL:
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
